'use strict';
const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const html=fs.readFileSync('app/src/main/assets/index.html','utf8');
const java=fs.readFileSync('app/src/main/java/com/singularity/c4nursery/MainActivity.java','utf8');
const start=html.indexOf('function c4HostSimDiagnostic(p){');
const end=html.indexOf('window.C4RuntimeEvent=(type,p)=>{',start);
assert.ok(start>=0&&end>start,'Native-result summarizer must precede WebView event dispatcher');
const summarize=vm.runInNewContext(html.slice(start,end)+'\nc4HostSimDiagnostic',{}, {timeout:250});
assert.equal(typeof summarize,'function');
function sample(roomOk,creditAccepted,creditStatus,goalStatus){
 return {requestId:'trial:test',room:{accepted:roomOk,executionSuccess:roomOk},c4Credit:{accepted:creditAccepted,status:creditStatus,goal_status:goalStatus}};
}
const success=summarize(sample(true,true,'SIM_SUCCESS','ACHIEVED_SIM'));
assert.equal(success.roomExecuted,true);
assert.equal(success.c4Accepted,true);
assert.equal(success.goalAchieved,true);
const rejected=summarize(sample(true,false,'REJECTED','ACHIEVED_SIM'));
assert.equal(rejected.roomExecuted,true);
assert.equal(rejected.goalAchieved,false);
const refuted=summarize(sample(true,true,'SIM_FAILURE','OPEN'));
assert.equal(refuted.roomExecuted,true);
assert.equal(refuted.c4Accepted,true);
assert.equal(refuted.goalAchieved,false);
const inProgress=summarize(sample(true,true,'SIM_SUCCESS','OPEN'));
assert.equal(inProgress.goalAchieved,false);
const fakeSuccess=summarize({requestId:'trial:test',room:{accepted:false,executionSuccess:false},c4Credit:{accepted:true,status:'SIM_SUCCESS',goal_status:'ACHIEVED_SIM'}});
assert.equal(fakeSuccess.goalAchieved,false);
const missing=summarize(null);
assert.equal(missing.roomExecuted,false);
assert.equal(missing.c4Accepted,false);
assert.equal(missing.goalAchieved,false);
assert.equal(missing.trainingEligible,false);
assert.equal(missing.origin,'HOST_DIAGNOSTIC_NOT_WORLD_EVIDENCE');
assert.ok(html.includes("if(type==='HOST_SIM_RESULT'){const d=c4HostSimDiagnostic(p);"));
assert.ok(html.includes("commit('C4_HOST_SIM_RESULT_DIAGNOSTIC',d)"));
assert.ok(html.indexOf("if(type==='HOST_SIM_RESULT'")<html.indexOf("if(!['REPLY','ASK','PUBLISH'"));
assert.ok(java.includes('emitRuntimeHost("HOST_SIM_RESULT",note)'),'Native host must publish read-only result');
assert.ok(java.includes('private String executeRoomActionTrusted('),'Executor stays Java-private');
console.log('C004-R5 HOST_SIM_RESULT DIAGNOSTICS PASS 9 scenarios/contracts');
