package com.singularity.c4nursery;

import android.app.*;import android.os.*;import android.webkit.*;import android.graphics.Color;
import android.content.*;import android.content.pm.PackageManager;import android.content.res.Configuration;
import android.net.Uri;import android.provider.MediaStore;import android.media.MediaRecorder;import android.media.projection.MediaProjection;import android.media.projection.MediaProjectionManager;import android.media.Image;import android.media.ImageReader;import android.hardware.display.DisplayManager;import android.hardware.display.VirtualDisplay;import android.graphics.Bitmap;import android.util.DisplayMetrics;
import org.json.JSONObject;import java.io.*;import java.util.*;import java.security.MessageDigest;import android.util.Base64;

public class MainActivity extends Activity {
 private WebView web; private SharedPreferences prefs; private MediaRecorder recorder; private BroadcastReceiver screenReceiver;
 private File audioFile; private Uri cameraUri; private final Object organismLock=new Object();
 private static final int PICK=4101,CAMERA=4102,MIC=4103,SCREEN=4104,STREAM=4105,ORGANISM=4106; private MediaProjectionManager projectionManager;

 @Override public void onCreate(Bundle b){
  super.onCreate(b); prefs=getSharedPreferences("c4_nursery",MODE_PRIVATE);
  web=new WebView(this); web.setBackgroundColor(Color.rgb(13,18,25));
  WebSettings s=web.getSettings(); s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);
  web.addJavascriptInterface(new NurseryBridge(),"NurseryNative");web.setWebViewClient(new WebViewClient());
  projectionManager=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);screenReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){try{JSONObject p=new JSONObject();p.put("phase",i.getStringExtra("phase"));p.put("sessionId",i.getStringExtra("sessionId"));p.put("capturedAt",i.getLongExtra("capturedAt",0));p.put("uri",i.getStringExtra("uri"));p.put("size",i.getLongExtra("size",0));emit("SCREEN_STREAM",p);}catch(Exception ignored){}}};IntentFilter sf=new IntentFilter(ScreenStreamService.ACTION_FRAME);if(Build.VERSION.SDK_INT>=33)registerReceiver(screenReceiver,sf,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(screenReceiver,sf);web.loadUrl("file:///android_asset/index.html");setContentView(web);
 }
 private void emit(String type,JSONObject payload){try{final String js="window.C4HostEvent&&window.C4HostEvent("+JSONObject.quote(type)+","+payload.toString()+")";runOnUiThread(()->web.evaluateJavascript(js,null));}catch(Exception ignored){}}
 private JSONObject attachment(String kind,String name,String mime,long size,String uri)throws Exception{JSONObject o=new JSONObject();o.put("kind",kind);o.put("name",name);o.put("mime",mime);o.put("size",size);o.put("uri",uri);o.put("capturedAt",System.currentTimeMillis());return o;}

 public final class NurseryBridge {
  @JavascriptInterface public String loadState(){return prefs.getString("state","{}");}
  @JavascriptInterface public boolean commitState(String json){try{new JSONObject(json);return prefs.edit().putString("state",json).commit();}catch(Exception e){return false;}}
  @JavascriptInterface public long now(){return System.currentTimeMillis();}
  @JavascriptInterface public String hostInfo(){try{JSONObject o=new JSONObject();o.put("sdk",Build.VERSION.SDK_INT);o.put("device",Build.MANUFACTURER+" "+Build.MODEL);o.put("orientation",getResources().getConfiguration().orientation==Configuration.ORIENTATION_LANDSCAPE?"landscape":"portrait");return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public String capabilities(){try{JSONObject o=new JSONObject();o.put("files",true);o.put("camera",getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_ANY));o.put("microphone",getPackageManager().hasSystemFeature(PackageManager.FEATURE_MICROPHONE));o.put("screenCapture",Build.VERSION.SDK_INT>=21);o.put("c4Transport",false);o.put("organismManager",true);o.put("runtimeLifecycle",true);return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public String readSourceChunk(String uriText,long offset,int requested){try{int n=Math.max(1,Math.min(requested,262144));Uri u=Uri.parse(uriText);InputStream in;if("file".equals(u.getScheme()))in=new FileInputStream(new File(u.getPath()));else in=getContentResolver().openInputStream(u);if(in==null)return "{\"ok\":false,\"error\":\"OPEN_FAILED\"}";long skipped=0;while(skipped<offset){long k=in.skip(offset-skipped);if(k<=0){if(in.read()==-1)break;k=1;}skipped+=k;}byte[] buf=new byte[n];int got=in.read(buf);in.close();JSONObject o=new JSONObject();o.put("ok",true);o.put("offset",offset);o.put("eof",got<0||got<n);if(got<0)got=0;o.put("length",got);o.put("base64",Base64.encodeToString(Arrays.copyOf(buf,got),Base64.NO_WRAP));return o.toString();}catch(Exception e){try{JSONObject o=new JSONObject();o.put("ok",false);o.put("error",e.getClass().getSimpleName());return o.toString();}catch(Exception x){return "{\"ok\":false}";}}}
  @JavascriptInterface public void inspectSource(String uriText){new Thread(()->{JSONObject out=new JSONObject();try{Uri u=Uri.parse(uriText);InputStream in="file".equals(u.getScheme())?new FileInputStream(new File(u.getPath())):getContentResolver().openInputStream(u);if(in==null)throw new IOException("OPEN_FAILED");MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] b=new byte[65536];int n;long total=0;boolean tooLarge=false;while((n=in.read(b))>0){total+=n;if(total>268435456L){tooLarge=true;break;}md.update(b,0,n);}in.close();out.put("uri",uriText);out.put("bytesScanned",total);if(tooLarge){out.put("ok",false);out.put("error","TOO_LARGE");}else{StringBuilder s=new StringBuilder();for(byte x:md.digest())s.append(String.format("%02x",x));out.put("ok",true);out.put("sourceId","sha256:"+s);}}catch(Exception e){try{out.put("ok",false);out.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}}emit("SOURCE_INSPECTED_NATIVE",out);}).start();}
  @JavascriptInterface public void pickOrganism(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/octet-stream","application/zip","application/json","text/plain"});startActivityForResult(i,ORGANISM);});}
  @JavascriptInterface public void clearOrganism(){prefs.edit().remove("organism_uri").remove("organism_sha").remove("organism_size").remove("organism_private_path").remove("organism_status").commit();try{JSONObject p=new JSONObject();p.put("active",false);emit("ORGANISM_CHANGED",p);}catch(Exception ignored){}}
  @JavascriptInterface public String runtimeInfo(){try{JSONObject o=new JSONObject();o.put("state","NOT_INSTALLED");o.put("transportReady",false);o.put("protocol","C4_APP_TRANSPORT_V1");o.put("organismLifecycle","C4_ORGANISM_RUNTIME_LIFECYCLE_V1");o.put("lastError",JSONObject.NULL);return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public String organismInfo(){try{JSONObject o=new JSONObject();String u=prefs.getString("organism_uri","");o.put("selected",!u.isEmpty());o.put("uri",u);o.put("sha256",prefs.getString("organism_sha",""));o.put("size",prefs.getLong("organism_size",0));o.put("privateCopy",prefs.getString("organism_private_path",""));o.put("validationState",prefs.getString("organism_status",u.isEmpty()?"EMPTY":"IMPORTED_UNVERIFIED"));o.put("runtimeAvailable",false);o.put("runtimeState","NOT_INSTALLED");return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public void pickFile(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);});}
  @JavascriptInterface public void capturePhoto(){runOnUiThread(()->{try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"c4_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);startActivityForResult(i,CAMERA);}catch(Exception e){JSONObject p=new JSONObject();try{p.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",p);}});}
  @JavascriptInterface public void startAudio(){runOnUiThread(()->startRecording());}
  @JavascriptInterface public void stopAudio(){runOnUiThread(()->stopRecording());}
  @JavascriptInterface public void captureScreen(){runOnUiThread(()->startActivityForResult(projectionManager.createScreenCaptureIntent(),SCREEN));}
  @JavascriptInterface public void startScreenStream(){runOnUiThread(()->startActivityForResult(projectionManager.createScreenCaptureIntent(),STREAM));}
  @JavascriptInterface public void stopScreenStream(){runOnUiThread(()->startService(new Intent(MainActivity.this,ScreenStreamService.class).setAction(ScreenStreamService.ACTION_STOP)));}
 }
 private void startRecording(){try{
  if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},MIC);return;}
  audioFile=new File(getFilesDir(),"audio_"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();
  recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setOutputFile(audioFile.getAbsolutePath());recorder.prepare();recorder.start();
  JSONObject p=new JSONObject();p.put("startedAt",System.currentTimeMillis());emit("AUDIO_STARTED",p);
 }catch(Exception e){recorder=null;JSONObject p=new JSONObject();try{p.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",p);}}
 private void stopRecording(){if(recorder==null)return;try{recorder.stop();recorder.release();recorder=null;emit("ATTACHMENT_READY",attachment("audio",audioFile.getName(),"audio/mp4",audioFile.length(),Uri.fromFile(audioFile).toString()));}catch(Exception e){try{recorder.release();}catch(Exception ignored){}recorder=null;}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==MIC&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startRecording();}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);try{
  if(r==ORGANISM&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,d.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}final String us=u.toString();new Thread(()->{try{InputStream in=getContentResolver().openInputStream(u);MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] b=new byte[65536];int n;long total=0;while((n=in.read(b))>0){total+=n;if(total>67108864L)throw new IOException("ORGANISM_TOO_LARGE");md.update(b,0,n);}in.close();StringBuilder s=new StringBuilder();for(byte x:md.digest())s.append(String.format("%02x",x));String lower=us.toLowerCase(Locale.ROOT);boolean extOk=lower.contains(".c4m");if(!extOk)throw new IOException("EXPECTED_C4M");File dir=new File(getFilesDir(),"organisms");if(!dir.exists()&&!dir.mkdirs())throw new IOException("ORGANISM_DIR_FAILED");File tmp=new File(dir,"import.tmp");File dst=new File(dir,"active.c4m");synchronized(organismLock){try(InputStream src=getContentResolver().openInputStream(u);FileOutputStream out=new FileOutputStream(tmp)){byte[] cp=new byte[65536];int z;while((z=src.read(cp))>0)out.write(cp,0,z);out.getFD().sync();}if(dst.exists()&&!dst.delete())throw new IOException("OLD_ORGANISM_DELETE_FAILED");if(!tmp.renameTo(dst))throw new IOException("ORGANISM_ATOMIC_MOVE_FAILED");}prefs.edit().putString("organism_uri",us).putString("organism_sha",s.toString()).putLong("organism_size",total).putString("organism_private_path",dst.getAbsolutePath()).putString("organism_status","IMPORTED_UNVERIFIED").commit();JSONObject p=new JSONObject();p.put("active",true);p.put("sha256",s.toString());p.put("size",total);p.put("validationState","IMPORTED_UNVERIFIED");p.put("runtimeAvailable",false);p.put("formatProbe","EXTENSION_ONLY");emit("ORGANISM_CHANGED",p);}catch(Exception e){JSONObject p=new JSONObject();try{p.put("error",e.getMessage());}catch(Exception ignored){}emit("ORGANISM_ERROR",p);}}).start();}
  if(r==PICK&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,d.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(SecurityException ignored){}String mime=getContentResolver().getType(u);emit("ATTACHMENT_READY",attachment("file","Документ",mime==null?"application/octet-stream":mime,-1,u.toString()));}
  if(r==CAMERA){if(c==RESULT_OK&&cameraUri!=null)emit("ATTACHMENT_READY",attachment("image","Фото","image/jpeg",-1,cameraUri.toString()));else if(cameraUri!=null)getContentResolver().delete(cameraUri,null,null);cameraUri=null;}
  if(r==SCREEN&&c==RESULT_OK&&d!=null)captureOneScreen(c,d);
  if(r==STREAM&&c==RESULT_OK&&d!=null){Intent s=new Intent(this,ScreenStreamService.class).setAction(ScreenStreamService.ACTION_START).putExtra(ScreenStreamService.EXTRA_CODE,c).putExtra(ScreenStreamService.EXTRA_DATA,d);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);}
 }catch(Exception e){JSONObject p=new JSONObject();try{p.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",p);}}
 private void captureOneScreen(int resultCode,Intent data){try{
  final MediaProjection mp=projectionManager.getMediaProjection(resultCode,data);DisplayMetrics dm=new DisplayMetrics();getWindowManager().getDefaultDisplay().getRealMetrics(dm);
  final int w=dm.widthPixels,h=dm.heightPixels,dpi=dm.densityDpi;final ImageReader ir=ImageReader.newInstance(w,h,android.graphics.PixelFormat.RGBA_8888,2);
  final VirtualDisplay vd=mp.createVirtualDisplay("C4ScreenShot",w,h,dpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,ir.getSurface(),null,null);
  ir.setOnImageAvailableListener(reader->{Image image=null;try{image=reader.acquireLatestImage();if(image==null)return;Image.Plane p=image.getPlanes()[0];java.nio.ByteBuffer buf=p.getBuffer();int pixelStride=p.getPixelStride(),rowStride=p.getRowStride(),rowPadding=rowStride-pixelStride*w;Bitmap padded=Bitmap.createBitmap(w+rowPadding/pixelStride,h,Bitmap.Config.ARGB_8888);padded.copyPixelsFromBuffer(buf);Bitmap bmp=Bitmap.createBitmap(padded,0,0,w,h);padded.recycle();File f=new File(getFilesDir(),"screen_"+System.currentTimeMillis()+".png");FileOutputStream os=new FileOutputStream(f);bmp.compress(Bitmap.CompressFormat.PNG,92,os);os.close();bmp.recycle();emit("ATTACHMENT_READY",attachment("screen",f.getName(),"image/png",f.length(),Uri.fromFile(f).toString()));}catch(Exception e){JSONObject x=new JSONObject();try{x.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",x);}finally{if(image!=null)image.close();vd.release();ir.close();mp.stop();}},new Handler(Looper.getMainLooper()));
 }catch(Exception e){JSONObject x=new JSONObject();try{x.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",x);}}
 @Override protected void onPause(){super.onPause();if(recorder!=null)stopRecording();}
 @Override protected void onDestroy(){if(screenReceiver!=null)unregisterReceiver(screenReceiver);super.onDestroy();}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else super.onBackPressed();}
}