package com.singularity.c4nursery;

import android.app.*;import android.os.*;import android.webkit.*;import android.graphics.Color;
import android.content.*;import android.content.pm.PackageManager;import android.content.res.Configuration;
import android.net.Uri;import android.provider.MediaStore;import android.provider.OpenableColumns;import android.media.MediaRecorder;import android.media.projection.MediaProjection;import android.media.projection.MediaProjectionManager;import android.media.Image;import android.media.ImageReader;import android.hardware.display.DisplayManager;import android.hardware.display.VirtualDisplay;import android.graphics.Bitmap;import android.util.DisplayMetrics;
import org.json.JSONObject;import org.json.JSONArray;import java.io.*;import java.util.*;import java.security.MessageDigest;import java.nio.charset.StandardCharsets;import android.database.Cursor;import android.util.Base64;

public class MainActivity extends Activity {
 private WebView web; private SharedPreferences prefs; private MediaRecorder recorder; private BroadcastReceiver screenReceiver;
 private File audioFile; private Uri cameraUri; private final Object organismLock=new Object();
 private static final int PICK=4101,CAMERA=4102,MIC=4103,SCREEN=4104,STREAM=4105,ORGANISM=4106; private MediaProjectionManager projectionManager;

 @Override public void onCreate(Bundle b){
  super.onCreate(b); prefs=getSharedPreferences("c4_nursery",MODE_PRIVATE);reconcileStartup();
  web=new WebView(this); web.setBackgroundColor(Color.rgb(13,18,25));
  WebSettings s=web.getSettings(); s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);
  web.addJavascriptInterface(new NurseryBridge(),"NurseryNative");web.setWebViewClient(new WebViewClient());
  projectionManager=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);screenReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){try{JSONObject p=new JSONObject();p.put("phase",i.getStringExtra("phase"));p.put("sessionId",i.getStringExtra("sessionId"));p.put("capturedAt",i.getLongExtra("capturedAt",0));p.put("uri",i.getStringExtra("uri"));p.put("size",i.getLongExtra("size",0));emit("SCREEN_STREAM",p);}catch(Exception ignored){}}};IntentFilter sf=new IntentFilter(ScreenStreamService.ACTION_FRAME);if(Build.VERSION.SDK_INT>=33)registerReceiver(screenReceiver,sf,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(screenReceiver,sf);web.loadUrl("file:///android_asset/index.html");setContentView(web);
 }
 private void reconcileStartup(){try{File org=new File(getFilesDir(),"organisms");File tmp=new File(org,"import.tmp");if(tmp.exists())tmp.delete();File src=new File(getFilesDir(),"sources");File[] leftovers=src.listFiles((d,n)->n.startsWith("import.tmp."));if(leftovers!=null)for(File x:leftovers)x.delete();if(prefs.getBoolean("runtime_running",false)){prefs.edit().putBoolean("runtime_running",false).putString("runtime_recovery","STALE_SESSION_STOPPED").commit();}String ap=prefs.getString("organism_private_path","");if(!ap.isEmpty()&&!new File(ap).isFile())prefs.edit().putString("organism_status","MISSING_PRIVATE_COPY").putString("runtime_recovery","ORGANISM_MISSING").commit();}catch(Exception e){prefs.edit().putString("runtime_recovery","RECONCILE_FAILED:"+e.getClass().getSimpleName()).commit();}}
 private void emit(String type,JSONObject payload){try{final String js="window.C4HostEvent&&window.C4HostEvent("+JSONObject.quote(type)+","+payload.toString()+")";runOnUiThread(()->web.evaluateJavascript(js,null));}catch(Exception ignored){}}
 private String displayName(Uri u,String fallback){try(Cursor q=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(q!=null&&q.moveToFirst()){String n=q.getString(0);if(n!=null&&!n.trim().isEmpty())return n;}}catch(Exception ignored){}return fallback;}
 private void importDiscreteSource(final String kind,final String name,final String mime,final Uri input){new Thread(()->{JSONObject p=new JSONObject();try{File root=new File(getFilesDir(),"sources");File store=new File(root,"store");if(!store.exists()&&!store.mkdirs())throw new IOException("SOURCE_STORE_FAILED");File tmp=new File(root,"import.tmp."+UUID.randomUUID());MessageDigest md=MessageDigest.getInstance("SHA-256");long total=0;try(InputStream in="file".equals(input.getScheme())?new FileInputStream(new File(input.getPath())):getContentResolver().openInputStream(input);FileOutputStream out=new FileOutputStream(tmp)){if(in==null)throw new IOException("SOURCE_OPEN_FAILED");byte[] b=new byte[65536];int n;while((n=in.read(b))>0){total+=n;if(total>536870912L)throw new IOException("SOURCE_TOO_LARGE");md.update(b,0,n);out.write(b,0,n);}out.getFD().sync();}StringBuilder hs=new StringBuilder();for(byte x:md.digest())hs.append(String.format("%02x",x));String sha=hs.toString();File dst=new File(store,sha+".bin");if(dst.exists()){if(dst.length()!=total)throw new IOException("SOURCE_DIGEST_COLLISION");if(!tmp.delete())throw new IOException("SOURCE_TEMP_CLEANUP_FAILED");}else if(!tmp.renameTo(dst))throw new IOException("SOURCE_PROMOTE_FAILED");p.put("kind",kind);p.put("name",name);p.put("mime",mime==null?"application/octet-stream":mime);p.put("size",total);p.put("sourceId","sha256:"+sha);p.put("uri",Uri.fromFile(dst).toString());p.put("capturedAt",System.currentTimeMillis());p.put("origin",kind.equals("file")?"USER":"SENSOR");p.put("phase","LIVE");p.put("independentEvidence",false);File meta=new File(store,sha+".json");File mt=new File(store,sha+".json.tmp");try(FileOutputStream mo=new FileOutputStream(mt)){byte[] mb=p.toString().getBytes(StandardCharsets.UTF_8);mo.write(mb);mo.getFD().sync();}if(meta.exists()&&!meta.delete())throw new IOException("SOURCE_META_REPLACE_FAILED");if(!mt.renameTo(meta))throw new IOException("SOURCE_META_PROMOTE_FAILED");emit("SOURCE_IMPORTED",p);}catch(Exception e){try{p.put("error",e.getMessage());}catch(Exception ignored){}emit("SOURCE_IMPORT_ERROR",p);}}).start();}
 private JSONObject attachment(String kind,String name,String mime,long size,String uri)throws Exception{JSONObject o=new JSONObject();o.put("kind",kind);o.put("name",name);o.put("mime",mime);o.put("size",size);o.put("uri",uri);o.put("capturedAt",System.currentTimeMillis());return o;}

 public final class NurseryBridge {
  @JavascriptInterface public String loadState(){return prefs.getString("state","{}");}
  @JavascriptInterface public boolean commitState(String json){try{new JSONObject(json);return prefs.edit().putString("state",json).commit();}catch(Exception e){return false;}}
  @JavascriptInterface public long now(){return System.currentTimeMillis();}
  @JavascriptInterface public String hostInfo(){try{JSONObject o=new JSONObject();o.put("sdk",Build.VERSION.SDK_INT);o.put("device",Build.MANUFACTURER+" "+Build.MODEL);o.put("orientation",getResources().getConfiguration().orientation==Configuration.ORIENTATION_LANDSCAPE?"landscape":"portrait");return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public String capabilities(){try{JSONObject o=new JSONObject();o.put("files",true);o.put("camera",getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_ANY));o.put("microphone",getPackageManager().hasSystemFeature(PackageManager.FEATURE_MICROPHONE));o.put("screenCapture",Build.VERSION.SDK_INT>=21);o.put("c4Transport",false);o.put("organismManager",true);o.put("runtimeLifecycle",true);return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public String listSources(){try{JSONArray a=new JSONArray();File store=new File(new File(getFilesDir(),"sources"),"store");File[] metas=store.listFiles((d,n)->n.endsWith(".json"));if(metas!=null){Arrays.sort(metas,(x,y)->Long.compare(y.lastModified(),x.lastModified()));for(File m:metas){try{byte[] b=new byte[(int)Math.min(m.length(),1048576L)];int n;try(FileInputStream in=new FileInputStream(m)){n=in.read(b);}if(n>0){JSONObject o=new JSONObject(new String(b,0,n,StandardCharsets.UTF_8));String id=o.optString("sourceId","").replace("sha256:","");File data=new File(store,id+".bin");o.put("available",data.isFile());o.put("storedBytes",data.isFile()?data.length():0);a.put(o);}}catch(Exception ignored){}}}return a.toString();}catch(Exception e){return "[]";}}
  @JavascriptInterface public String readSourceChunk(String uriText,long offset,int requested){try{int n=Math.max(1,Math.min(requested,262144));Uri u=Uri.parse(uriText);InputStream in;if("file".equals(u.getScheme()))in=new FileInputStream(new File(u.getPath()));else in=getContentResolver().openInputStream(u);if(in==null)return "{\"ok\":false,\"error\":\"OPEN_FAILED\"}";long skipped=0;while(skipped<offset){long k=in.skip(offset-skipped);if(k<=0){if(in.read()==-1)break;k=1;}skipped+=k;}byte[] buf=new byte[n];int got=in.read(buf);in.close();JSONObject o=new JSONObject();o.put("ok",true);o.put("offset",offset);o.put("eof",got<0||got<n);if(got<0)got=0;o.put("length",got);o.put("base64",Base64.encodeToString(Arrays.copyOf(buf,got),Base64.NO_WRAP));return o.toString();}catch(Exception e){try{JSONObject o=new JSONObject();o.put("ok",false);o.put("error",e.getClass().getSimpleName());return o.toString();}catch(Exception x){return "{\"ok\":false}";}}}
  @JavascriptInterface public void inspectSource(String uriText){new Thread(()->{JSONObject out=new JSONObject();try{Uri u=Uri.parse(uriText);InputStream in="file".equals(u.getScheme())?new FileInputStream(new File(u.getPath())):getContentResolver().openInputStream(u);if(in==null)throw new IOException("OPEN_FAILED");MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] b=new byte[65536];int n;long total=0;boolean tooLarge=false;while((n=in.read(b))>0){total+=n;if(total>268435456L){tooLarge=true;break;}md.update(b,0,n);}in.close();out.put("uri",uriText);out.put("bytesScanned",total);if(tooLarge){out.put("ok",false);out.put("error","TOO_LARGE");}else{StringBuilder s=new StringBuilder();for(byte x:md.digest())s.append(String.format("%02x",x));out.put("ok",true);out.put("sourceId","sha256:"+s);}}catch(Exception e){try{out.put("ok",false);out.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}}emit("SOURCE_INSPECTED_NATIVE",out);}).start();}
  @JavascriptInterface public void pickOrganism(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/octet-stream","application/zip","application/json","text/plain"});startActivityForResult(i,ORGANISM);});}
  @JavascriptInterface public void clearOrganism(){if(prefs.getBoolean("runtime_running",false))return;prefs.edit().remove("organism_uri").remove("organism_sha").remove("organism_size").remove("organism_private_path").remove("organism_status").commit();try{JSONObject p=new JSONObject();p.put("active",false);emit("ORGANISM_CHANGED",p);}catch(Exception ignored){}}
  @JavascriptInterface public String listOrganisms(){try{JSONArray a=new JSONArray();File store=new File(new File(getFilesDir(),"organisms"),"store");String active=prefs.getString("organism_sha","");File[] fs=store.listFiles((d,n)->n.endsWith(".c4m"));if(fs!=null){Arrays.sort(fs,Comparator.comparing(File::getName));for(File x:fs){String sha=x.getName().substring(0,x.getName().length()-4);JSONObject o=new JSONObject();o.put("id","sha256:"+sha);o.put("sha256",sha);o.put("size",x.length());o.put("state",sha.equals(active)?prefs.getString("organism_status","IMPORTED_UNVERIFIED"):"INSTALLED");o.put("active",sha.equals(active));o.put("runtimeBound",false);a.put(o);}}return a.toString();}catch(Exception e){return "[]";}}
  @JavascriptInterface public boolean activateOrganism(String sha){try{if(prefs.getBoolean("runtime_running",false))return false;if(sha==null||!sha.matches("[0-9a-fA-F]{64}"))return false;File f=new File(new File(new File(getFilesDir(),"organisms"),"store"),sha.toLowerCase(Locale.ROOT)+".c4m");if(!f.isFile())return false;boolean ok=prefs.edit().putString("organism_sha",sha.toLowerCase(Locale.ROOT)).putString("organism_private_path",f.getAbsolutePath()).putLong("organism_size",f.length()).putString("organism_status","IMPORTED_UNVERIFIED").commit();if(ok){JSONObject p=new JSONObject();p.put("active",true);p.put("sha256",sha.toLowerCase(Locale.ROOT));p.put("size",f.length());p.put("validationState","IMPORTED_UNVERIFIED");emit("ORGANISM_CHANGED",p);}return ok;}catch(Exception e){return false;}}
  @JavascriptInterface public String recoveryInfo(){try{JSONObject o=new JSONObject();File dir=new File(getFilesDir(),"organisms");String ap=prefs.getString("organism_private_path","");File active=ap.isEmpty()?new File(dir,"__none__"):new File(ap),prev=new File(dir,"previous.c4m"),tmp=new File(dir,"import.tmp");o.put("activeExists",active.isFile());o.put("activeBytes",active.isFile()?active.length():0);o.put("previousExists",prev.isFile());o.put("previousBytes",prev.isFile()?prev.length():0);o.put("orphanTemp",tmp.exists());o.put("needsReconcile",tmp.exists());return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public String verifySandboxReceipt(String json){try{JSONObject q=new JSONObject(json);String experiment=q.optString("experiment","");JSONObject o=new JSONObject();o.put("accepted",false);o.put("origin","SANDBOX");o.put("phase","LIVE");o.put("executionSuccess",true);if("CAUSAL_MECHANICS_V2".equals(experiment)){String m=q.optString("mechanism","");int force=q.optInt("force",0);boolean valid=("PUSH".equals(m)||"RAMP".equals(m)||"SPRING".equals(m))&&(force==1||force==2);if(!valid){o.put("error","INVALID_WORLD_ACTION");return o.toString();}boolean outcome="PUSH".equals(m)?force==2:"RAMP".equals(m)?force==1:force==2;boolean prediction=q.optBoolean("prediction");String variant=m+"_F"+force;o.put("accepted",true);o.put("experiment",experiment);o.put("mechanism",m);o.put("challengeVariant",variant);o.put("prediction",prediction);o.put("outcome",outcome);o.put("predictionCorrect",prediction==outcome);String sig=sha256Text(experiment+"|"+variant+"|"+outcome);boolean first=!prefs.getBoolean("sandbox_sig_"+sig,false);if(first)prefs.edit().putBoolean("sandbox_sig_"+sig,true).commit();o.put("evidenceSignature",sig);o.put("independentEvidence",first);o.put("replay",!first);return o.toString();}if("SEQUENCE_MEMORY_V1".equals(experiment)){JSONArray seq=q.optJSONArray("sequence"),input=q.optJSONArray("input");if(seq==null||input==null||seq.length()<1||seq.length()>6){o.put("error","INVALID_MEMORY_CHALLENGE");return o.toString();}boolean match=seq.length()==input.length();if(match)for(int i=0;i<seq.length();i++)if(seq.optInt(i,-1)!=input.optInt(i,-2)){match=false;break;}o.put("accepted",true);o.put("experiment",experiment);o.put("challengeId",q.optString("challengeId",""));o.put("challengeVariant","L"+seq.length());o.put("outcome",match?"match":"mismatch");o.put("solved",match);o.put("independentEvidence",false);o.put("evidenceSignature",sha256Text(experiment+"|"+q.optString("challengeId","")+"|"+match));return o.toString();}o.put("error","UNKNOWN_EXPERIMENT");return o.toString();}catch(Exception e){return "{\"accepted\":false,\"error\":\"INVALID_RECEIPT_REQUEST\"}";}}
  private String sha256Text(String s)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] d=md.digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();for(byte x:d)b.append(String.format("%02x",x));return b.toString();}
  @JavascriptInterface public String runtimeCommand(String json){try{JSONObject q=new JSONObject(json);String type=q.optString("type","");String requestId=q.optString("requestId","");Set<String> allowed=new HashSet<>(Arrays.asList("OPEN_SESSION","CLOSE_SESSION","USER_MESSAGE","BEGIN_SOURCE","APPEND_SOURCE","END_SOURCE","TICK","ACTION_RECEIPT","SENSORY_SESSION_START","SENSORY_SESSION_FRAME","SENSORY_SESSION_STOP","CHECKPOINT"));JSONObject o=new JSONObject();o.put("accepted",false);o.put("type",type);if(!requestId.isEmpty())o.put("requestId",requestId);if(!allowed.contains(type)){o.put("error","COMMAND_NOT_ALLOWED");return o.toString();}if("OPEN_SESSION".equals(type)){String path=prefs.getString("organism_private_path","");String sha=prefs.getString("organism_sha","");if(path.isEmpty()||sha.isEmpty()||!new File(path).isFile()){o.put("error","ORGANISM_NOT_READY");o.put("runtimeState","NOT_INSTALLED");return o.toString();}}if(!"OPEN_SESSION".equals(type)&&!"CLOSE_SESSION".equals(type)&&!prefs.getBoolean("runtime_running",false)){o.put("error","SESSION_NOT_RUNNING");o.put("runtimeState","NOT_INSTALLED");return o.toString();}o.put("error","RUNTIME_NOT_INSTALLED");o.put("runtimeState","NOT_INSTALLED");return o.toString();}catch(Exception e){try{JSONObject o=new JSONObject();o.put("accepted",false);o.put("error","INVALID_COMMAND");return o.toString();}catch(Exception x){return "{\"accepted\":false}";}}}
  @JavascriptInterface public String runtimeInfo(){try{JSONObject o=new JSONObject();boolean running=prefs.getBoolean("runtime_running",false);o.put("state",running?"RUNNING":"NOT_INSTALLED");o.put("transportReady",running);o.put("protocol","C4_APP_TRANSPORT_V1");o.put("adapter","C4_RUNTIME_ADAPTER_V1");o.put("organismLifecycle","C4_ORGANISM_RUNTIME_LIFECYCLE_V1");o.put("sessionId",running?prefs.getString("runtime_session_id",""):JSONObject.NULL);o.put("runtimeAvailable",false);o.put("lastError",running?JSONObject.NULL:"RUNTIME_NOT_INSTALLED");o.put("recovery",prefs.getString("runtime_recovery","CLEAN"));return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public String organismInfo(){try{JSONObject o=new JSONObject();String u=prefs.getString("organism_uri","");o.put("selected",!u.isEmpty());o.put("uri",u);o.put("sha256",prefs.getString("organism_sha",""));o.put("size",prefs.getLong("organism_size",0));o.put("privateCopy",prefs.getString("organism_private_path",""));o.put("validationState",prefs.getString("organism_status",u.isEmpty()?"EMPTY":"IMPORTED_UNVERIFIED"));o.put("runtimeAvailable",false);o.put("runtimeState","NOT_INSTALLED");return o.toString();}catch(Exception e){return "{}";}}
  @JavascriptInterface public void pickFile(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);});}
  @JavascriptInterface public void capturePhoto(){runOnUiThread(()->{try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"c4_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);startActivityForResult(i,CAMERA);}catch(Exception e){JSONObject p=new JSONObject();try{p.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",p);}});}
  @JavascriptInterface public void startAudio(){runOnUiThread(()->startRecording());}
  @JavascriptInterface public void stopAudio(){runOnUiThread(()->stopRecording());}
  @JavascriptInterface public void captureScreen(){runOnUiThread(()->startActivityForResult(projectionManager.createScreenCaptureIntent(),SCREEN));}
  @JavascriptInterface public void startScreenStream(){runOnUiThread(()->startActivityForResult(projectionManager.createScreenCaptureIntent(),STREAM));}
  @JavascriptInterface public void stopScreenStream(){runOnUiThread(()->startService(new Intent(MainActivity.this,ScreenStreamService.class).setAction(ScreenStreamService.ACTION_STOP)));}
 }
 private void startRecording(){try{
  if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},MIC);return;}
  audioFile=new File(getFilesDir(),"audio_"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();
  recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setOutputFile(audioFile.getAbsolutePath());recorder.prepare();recorder.start();
  JSONObject p=new JSONObject();p.put("startedAt",System.currentTimeMillis());emit("AUDIO_STARTED",p);
 }catch(Exception e){recorder=null;JSONObject p=new JSONObject();try{p.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",p);}}
 private void stopRecording(){if(recorder==null)return;try{recorder.stop();recorder.release();recorder=null;importDiscreteSource("audio",audioFile.getName(),"audio/mp4",Uri.fromFile(audioFile));}catch(Exception e){try{recorder.release();}catch(Exception ignored){}recorder=null;}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==MIC&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startRecording();}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);try{
  if(r==ORGANISM&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,d.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}final String us=u.toString();new Thread(()->{try{InputStream in=getContentResolver().openInputStream(u);MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] b=new byte[65536];int n;long total=0;while((n=in.read(b))>0){total+=n;if(total>67108864L)throw new IOException("ORGANISM_TOO_LARGE");md.update(b,0,n);}in.close();StringBuilder s=new StringBuilder();for(byte x:md.digest())s.append(String.format("%02x",x));String lower=us.toLowerCase(Locale.ROOT);boolean extOk=lower.contains(".c4m");if(!extOk)throw new IOException("EXPECTED_C4M");File dir=new File(getFilesDir(),"organisms");if(!dir.exists()&&!dir.mkdirs())throw new IOException("ORGANISM_DIR_FAILED");File tmp=new File(dir,"import.tmp");File store=new File(dir,"store");if(!store.exists()&&!store.mkdirs())throw new IOException("ORGANISM_STORE_FAILED");File dst=new File(store,s.toString()+".c4m");synchronized(organismLock){try(InputStream src=getContentResolver().openInputStream(u);FileOutputStream out=new FileOutputStream(tmp)){byte[] cp=new byte[65536];int z;while((z=src.read(cp))>0)out.write(cp,0,z);out.getFD().sync();}if(dst.exists()){if(tmp.length()!=dst.length())throw new IOException("DIGEST_COLLISION_SIZE_MISMATCH");if(!tmp.delete())throw new IOException("TEMP_CLEANUP_FAILED");}else if(!tmp.renameTo(dst))throw new IOException("ORGANISM_ATOMIC_MOVE_FAILED");}prefs.edit().putString("organism_uri",us).putString("organism_sha",s.toString()).putLong("organism_size",total).putString("organism_private_path",dst.getAbsolutePath()).putString("organism_status","IMPORTED_UNVERIFIED").commit();JSONObject p=new JSONObject();p.put("active",true);p.put("sha256",s.toString());p.put("size",total);p.put("validationState","IMPORTED_UNVERIFIED");p.put("runtimeAvailable",false);p.put("formatProbe","EXTENSION_ONLY");emit("ORGANISM_CHANGED",p);}catch(Exception e){JSONObject p=new JSONObject();try{p.put("error",e.getMessage());}catch(Exception ignored){}emit("ORGANISM_ERROR",p);}}).start();}
  if(r==PICK&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,d.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(SecurityException ignored){}String mime=getContentResolver().getType(u);importDiscreteSource("file","Документ",mime==null?"application/octet-stream":mime,u);}
  if(r==CAMERA){if(c==RESULT_OK&&cameraUri!=null)importDiscreteSource("image","Фото","image/jpeg",cameraUri);else if(cameraUri!=null)getContentResolver().delete(cameraUri,null,null);cameraUri=null;}
  if(r==SCREEN&&c==RESULT_OK&&d!=null)captureOneScreen(c,d);
  if(r==STREAM&&c==RESULT_OK&&d!=null){Intent s=new Intent(this,ScreenStreamService.class).setAction(ScreenStreamService.ACTION_START).putExtra(ScreenStreamService.EXTRA_CODE,c).putExtra(ScreenStreamService.EXTRA_DATA,d);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);}
 }catch(Exception e){JSONObject p=new JSONObject();try{p.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",p);}}
 private void captureOneScreen(int resultCode,Intent data){try{
  final MediaProjection mp=projectionManager.getMediaProjection(resultCode,data);DisplayMetrics dm=new DisplayMetrics();getWindowManager().getDefaultDisplay().getRealMetrics(dm);
  final int w=dm.widthPixels,h=dm.heightPixels,dpi=dm.densityDpi;final ImageReader ir=ImageReader.newInstance(w,h,android.graphics.PixelFormat.RGBA_8888,2);
  final VirtualDisplay vd=mp.createVirtualDisplay("C4ScreenShot",w,h,dpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,ir.getSurface(),null,null);
  ir.setOnImageAvailableListener(reader->{Image image=null;try{image=reader.acquireLatestImage();if(image==null)return;Image.Plane p=image.getPlanes()[0];java.nio.ByteBuffer buf=p.getBuffer();int pixelStride=p.getPixelStride(),rowStride=p.getRowStride(),rowPadding=rowStride-pixelStride*w;Bitmap padded=Bitmap.createBitmap(w+rowPadding/pixelStride,h,Bitmap.Config.ARGB_8888);padded.copyPixelsFromBuffer(buf);Bitmap bmp=Bitmap.createBitmap(padded,0,0,w,h);padded.recycle();File f=new File(getFilesDir(),"screen_"+System.currentTimeMillis()+".png");FileOutputStream os=new FileOutputStream(f);bmp.compress(Bitmap.CompressFormat.PNG,92,os);os.close();bmp.recycle();emit("ATTACHMENT_READY",attachment("screen",f.getName(),"image/png",f.length(),Uri.fromFile(f).toString()));}catch(Exception e){JSONObject x=new JSONObject();try{x.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",x);}finally{if(image!=null)image.close();vd.release();ir.close();mp.stop();}},new Handler(Looper.getMainLooper()));
 }catch(Exception e){JSONObject x=new JSONObject();try{x.put("error",e.getClass().getSimpleName());}catch(Exception ignored){}emit("MEDIA_ERROR",x);}}
 @Override protected void onPause(){super.onPause();if(recorder!=null)stopRecording();}
 @Override protected void onDestroy(){if(screenReceiver!=null)unregisterReceiver(screenReceiver);super.onDestroy();}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else super.onBackPressed();}
}